version: 0.2

cache:
  paths:
    - 'frontend/node_modules/**/*'

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install -g @openapitools/openapi-generator-cli
      - cd frontend
      - npm install
      - npm install --save-dev jest @testing-library/react @testing-library/jest-dom jest-environment-jsdom
      - npm install -g jest
      - cd ..

  pre_build:
    commands:
      - echo Writing setupTests.js...
      - mkdir -p frontend/src
      - |
        cat <<EOF > frontend/src/setupTests.js
        // Jest setup file
        // Using require instead of import for compatibility
        require('@testing-library/jest-dom');
        EOF
        
      - echo Writing jest.config.js...
      - |
        cat <<EOF > frontend/jest.config.js
        module.exports = {
          testEnvironment: 'jsdom',
          setupFilesAfterEnv: ['<rootDir>/src/setupTests.js'],
          moduleFileExtensions: ['js', 'jsx', 'ts', 'tsx', 'json'],
          testMatch: ['**/testapi/*.test.js', '**/__tests__/**/*.test.js'],
          collectCoverage: true,
          coverageDirectory: 'coverage',
          testPathIgnorePatterns: ['/node_modules/']
        };
        EOF

      - echo Export OpenAPI spec from API Gateway...
      - aws apigateway get-export --rest-api-id $API_ID --stage-name $STAGE --export-type oas30 --accepts application/json openapi.json
      - |
        if [ ! -f openapi.json ]; then
          echo "Error: Failed to export openapi.json"
          exit 1
        fi

      - echo Generating TypeScript Axios client from OpenAPI spec...
      - openapi-generator-cli generate -i openapi.json -g typescript-axios -o frontend/src/api

      - echo Generating Jest test files from API...
      - cp generate-simple-tests.js frontend/
      - cd frontend
      - node generate-simple-tests.js
      - cd ..

  build:
    commands:
      - echo Running frontend tests with coverage...
      - cd frontend
      - CI=true npm test -- --passWithNoTests || echo "Tests failed but continuing build"
      - echo Build frontend app...
      - npm run build
      - cd ..

artifacts:
  files:
    - frontend/build/**/*
    - frontend/coverage/**/*